"""create model

Revision ID: 2db777518da5
Revises: 
Create Date: 2022-04-19 22:33:21.171118

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2db777518da5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("last_name", sa.String(length=511), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=511), nullable=True),
        sa.Column("api_key", sa.String(length=511), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
