"""populate db

Revision ID: 933a2f4677a8
Revises: 2db777518da5
Create Date: 2022-04-20 19:29:49.788379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933a2f4677a8'
down_revision = '2db777518da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    # ### end Alembic commands ###
